name: Build gaster

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-libusb-linux:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y aria2 libusb-1.0-0-dev xxd
          sudo apt remove -y libssl-dev
          aria2c https://www.openssl.org/source/openssl-1.1.1q.tar.gz
          tar -zxvf openssl-1.1.1q.tar.gz
          cd openssl-1.1.1q
          ./Configure no-ssl3-method enable-ec_nistp_64_gcc_128 linux-x86_64 "-Wa,--noexecstack -fPIC"
          make depend -j4
          make -j4
          sudo make install_sw install_ssldirs
          sudo rm -rf /usr/local/lib/libcrypto.so* /usr/local/lib/libssl.so*
          cd ..
      
      - name: Build
        run: |
          make libusb -j4
          echo -n "$(git rev-parse HEAD | tr -d '\n')" > latest_build_sha.txt
          echo -n "$(git rev-list --count HEAD | tr -d '\n')" > latest_build_num.txt
          
      - name: Upload versioning
        uses: actions/upload-artifact@v2
        with:
          name: Versioning
          path: |
            ${{ github.workspace }}/latest_build_sha.txt
            ${{ github.workspace }}/latest_build_num.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: gaster-Linux
          path: gaster

          if-no-files-found: warn
          retention-days: 30

  build-macOS:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          make macos -j4
          echo -n "$(git rev-parse HEAD | tr -d '\n')" > latest_build_sha.txt
          echo -n "$(git rev-list --count HEAD | tr -d '\n')" > latest_build_num.txt

      - name: Upload versioning
        uses: actions/upload-artifact@v2
        with:
          name: Versioning
          path: |
            ${{ github.workspace }}/latest_build_sha.txt
            ${{ github.workspace }}/latest_build_num.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: gaster-Darwin
          path: gaster

          if-no-files-found: warn
          retention-days: 30
